GunGame Percentage Meter
R2Northstar/NorthstarMods pull request #114
Opened 2022-01-14 03:29 UTC by connieprice

# Added a percentage meter to GunGame, which also displays the next weapon!

https://user-images.githubusercontent.com/5340283/149446727-da0e96eb-a77f-4fc2-9ca1-53fdc249da1c.mp4

- New GunGame meter, by default, everything acts precisely like before. It just adds some visual flair.
- Support for varying reward percentages for Kills, Assists and Executions to let server owners mix up their gameplay a bit more.
- Actual assist support, by default providing no points, but the option is now there. ( Feel free to change this default if you feel it deserves one. )
- Replaced the Archer with a primary-enabled melee, finally no more Archer blocking half the screen.
- Gave the pilot melees "allow_as_primary" mods so they can be used as empty slot weapons.

2022-01-14 03:55 UTC, VITALISED commented
is there anything that can be done about the weapon icons being stretched?

2022-01-14 20:19 UTC, connieprice commented
Just reiterating what I said on discord, I'd fix stretching if I could, unfortunately that's hidden in the depths of RUI for the time being.

2022-01-15 02:28 UTC, VITALISED requested changes
These changes are good, but did you mean to commit your weapon keyvalue changes?

2022-01-15 02:37 UTC, VITALISED commented
Oh my bad sorry lmfao

2022-01-15 04:21 UTC, abarichello commented on Northstar.Custom/mod/scripts/vscripts/gamemodes/sh_gamemode_gg.gnut
>  	GunGameWeapon ggPulseBlade = { weapon = "mp_weapon_grenade_sonar", mods = [ "pas_power_cell", "amped_tacticals" ], offhandSlot = 0 }
```suggestion
	GunGameWeapon ggPulseBlade = { weapon = "mp_weapon_grenade_sonar", mods = [ "pas_power_cell", "amped_tacticals" ], offhandSlot = OFFHAND_SPECIAL }
```

Moving pulse blade to its normal slot

2022-01-15 15:47 UTC, merged