Fix Armbadge Oddities
R2Northstar/NorthstarMods pull request #173
Opened 2022-01-29 22:18 UTC by MiloAkerman

Resolves #161 
Resolves #153

2022-01-30 04:30 UTC, BobTheBob9 requested changes

2022-01-30 04:30 UTC, BobTheBob9 commented on Northstar.Custom/mod/scripts/vscripts/titan/sh_titan.gnut
> +    if(armBadge == null)
could you change this to an !IsValid check?

2022-01-30 16:15 UTC, MiloAkerman commented
Done

2022-01-31 14:38 UTC, MiloAkerman commented
@BobTheBob9 is the syntax right? As barichello pointed out I don't know if this is a native issue or collateral from some Northstar mod because I wasn't able to find any reports for this specific crash.

2022-02-01 00:07 UTC, MiloAkerman commented
Now also resolves #175

2022-02-01 00:10 UTC, MiloAkerman commented
Seeing as I have no idea what the intended behavior should be for negative XP i decided to just go back to 0. Could also make it positive with `*= -1` but that seems a little scuffed

2022-02-01 00:15 UTC, MiloAkerman commented
Resolves #163

2022-02-01 00:18 UTC, MiloAkerman commented
Wtf why did the empty lines on `_xp.gnut` get scuffed

2022-02-01 16:01 UTC, MiloAkerman commented
Now resolves one of the three issues in #43

2022-02-03 20:01 UTC, abarichello commented
I don't think the fixes implemented in `_anim.gnut` and `_titan_transfer.nut` tackle the root of these problems, sure adding validity checks might prevent the game from crashing but that will probably move the crash somewhere else. Since that's the best we have for now I'll merge it anyways. Thanks

2022-02-03 20:02 UTC, merged

2022-02-04 13:00 UTC, MiloAkerman commented
The change in `_anim.gnut` is more so a fix of an issue that should theoretically be native. I didn't add or remove any functionality, just changed a `null` check to a hopefully more in-depth `IsValid()` check