Advanced chat hooks
R2Northstar/NorthstarMods pull request #217
Opened 2022-02-15 13:02 UTC by cpdt

This is the mod side of https://github.com/R2Northstar/NorthstarLauncher/pull/74.

### New server functions

 - `void Chat_Impersonate(entity player, string text, bool isTeamChat)` - impersonate a player sending a message.
 - `void Chat_PrivateMessage(entity fromPlayer, entity toPlayer, string text, bool whisper)` - send a message from a player that's shown to a single recipient. Will be shown with a [WHISPER] tag if whisper is set.
 - `void Chat_ServerBroadcast(string text)` - send a server message to all players.
 - `void Chat_ServerPrivateMessage(entity toPlayer, string text, bool whisper)` - send a server message to a single recipient. Will be shown with a [WHISPER] tag if whisper is set.

### New client functions

 - `void Chat_NetworkWriteLine(string text)` - writes a line of text in network chat
 - `void Chat_GameWriteLine(string text)` - writes a line of text to in-game chat
 - `void Chat_NetworkWrite(string text)` - appends a string to network chat
 - `void Chat_GameWrite(string text)` - appends a string to in-game chat

2022-02-16 10:10 UTC, emma-miler approved these changes

2022-02-18 12:31 UTC, x3Karma approved these changes

2022-02-20 17:49 UTC, abarichello approved these changes

2022-02-21 12:18 UTC, emma-miler approved these changes

2022-02-21 12:24 UTC, emma-miler requested changes

2022-02-21 12:24 UTC, emma-miler commented on Northstar.CustomServers/mod/scripts/vscripts/_custom_codecallbacks.gnut
> +	NSSendMessage(player.GetPlayerIndex(), localMessage.message, localMessage.isTeam)
IMO all mods subscribed to the message handler should see the message, even if an earlier mod decides it wants to block it. You could simply `|` `localMessage.shouldBlock` like in my original implementation as discussed on discord ^^

2022-02-21 12:28 UTC, emma-miler approved these changes

2022-02-21 22:33 UTC, merged