Add arrow nav to maps menu + fix server browser nav
R2Northstar/NorthstarMods pull request #248
Opened 2022-02-24 20:44 UTC by F1F7Y

- Selects 1st server when you open server browser
  - Allows for full keyboard / controller navigation
- Adds arrow nav to maps menu

2022-02-26 23:02 UTC, abarichello requested changes
This new map menu is looking really good, please fix the formatting issues so we can use it in 1.6.0

2022-02-27 12:12 UTC, F1F7Y commented on Northstar.Client/mod/resource/ui/menus/panels/map_grid.res
> +		pin_to_sibling					GridInfo1x3
:dread:

2022-02-27 12:13 UTC, F1F7Y commented on Northstar.Client/mod/scripts/vscripts/ui/menu_map_select.nut
> -	int mapID = int( Hud_GetScriptID( Hud_GetParent( button ) ) )
wat

2022-02-27 12:14 UTC, F1F7Y commented on Northstar.Client/mod/scripts/vscripts/ui/menu_map_select.nut
> +	if ( file.mapsArrayFiltered.len() <= BUTTONS_PER_PAGE || file.mapsArrayFiltered.len() <= 12 ) return
should be fine now

2022-02-28 20:08 UTC, merged

2022-02-28 20:09 UTC, abarichello approved these changes
Thanks