Add mod-side URI Handling and invite code
R2Northstar/NorthstarMods pull request #259
Opened 2022-03-05 00:47 UTC by emma-miler

Linked to https://github.com/R2Northstar/NorthstarLauncher/pull/104

2022-03-12 22:57 UTC, abarichello requested changes

2022-03-12 22:57 UTC, abarichello commented on Northstar.Client/mod/scripts/vscripts/ui/menu_lobby.nut
> +	//Hud_AddEventHandler( generateInviteButton, UIE_CLICK, GenerateServerInvite )
```suggestion
```
Unused code

2022-03-12 22:57 UTC, abarichello commented on Northstar.Client/mod/scripts/vscripts/ui/menu_main.nut
> +}
This part is not following the project's code style 😉

2022-03-12 22:57 UTC, abarichello commented on Northstar.Client/mod/resource/northstar_client_localisation_portuguese.txt
> +		"NS_INVITE_GENERATE_SUCCESS_BODY"       "La invitacion ha sido copiada al PortaPapeles"
This is spanish, not portuguese lol

2022-03-13 18:36 UTC, abarichello commented on Northstar.Client/mod/resource/northstar_client_localisation_portuguese.txt
> +		"NS_INVITE_GENERATE_SUCCESS_BODY"       "La invitacion ha sido copiada al PortaPapeles"
```suggestion
		"NS_INVITE_MENU_HEADER" "Convites"
		"NS_INVITE_GENERATE_SERVER_BUTTON" "Criar convite de Servidor"
		"NS_INVITE_GENERATE_PARTY_BUTTON" "Criar convite de Grupo"
		"NS_INVITE_JOIN_BUTTON" "Aceitar convite"
		"NS_INVITE_JOIN_HEADER" "Aceitar convite"
		"NS_INVITE_JOIN_BODY" "Você recebeu um convite para entrar no servidor: %1"
		"NS_PARTY_INVITE_HEADER" "Entrar no grupo"
		"NS_PARTY_INVITE_BODY" "Você recebeu um convite do grupo: %1"
		"NS_INVITE_GENERATE_FAILURE_HEADER" "Não foi possível criar o convite"
		"NS_INVITE_GENERATE_FAILURE_BODY" "Ocorreu um erro ao criar o convite: %1"
		"NS_INVITE_GENERATE_SUCCESS_HEADER" "Convite criado"
		"NS_INVITE_GENERATE_SUCCESS_BODY" "O link de convite foi copiado"
```

2022-09-24 23:40 UTC, emma-miler commented
Planning to rework this against current master when i have the time. Drafting this for now

2023-10-01 18:12 UTC, ASpoonPlaysGames commented
Closing as stale, and linked PR is also closed. Feel free to reopen though if you want

2023-10-01 18:12 UTC, closed without merging