Halfway decent fix to allow changing of minimap size and zoom midgame
R2Northstar/NorthstarMods pull request #265
Opened 2022-03-11 17:52 UTC by JMM889901

it errr does the thing and errrr minimap get bigger :clueless:

2022-06-22 12:13 UTC, BobTheBob9 requested changes

2022-06-22 12:13 UTC, BobTheBob9 commented on Northstar.Client/mod/scripts/vscripts/client/cl_minimap.gnut
> +global function DumbMinimapFunction
maybe remove this lol

2022-06-23 10:58 UTC, JMM889901 commented on Northstar.Client/mod/scripts/vscripts/client/cl_minimap.gnut
> +global function DumbMinimapFunction
Forgor

2022-10-17 17:16 UTC, JMM889901 commented
No merge? ![image](https://user-images.githubusercontent.com/41163714/196241394-493bc6b3-5958-432d-ba9b-13b3c62f1a63.jpeg)

2022-10-17 18:13 UTC, uniboi approved these changes
![image](https://user-images.githubusercontent.com/64006268/196251394-6d4aaf5a-dbe2-467d-83eb-067f394c1abb.png)
works in testing

2022-10-22 02:43 UTC, merged