Various CTF fixes
R2Northstar/NorthstarMods pull request #282
Opened 2022-03-29 17:21 UTC by ASpoonPlaysGames

Fixing the following:
- Various crashes
- Being able to capture flags during epilogue and halftime #266 
- Weird flag spawning stuff

Also I have opted to destroy the flags and the flag bases when the epilogue is triggered, as I believe that's what happens in vanilla? Would be nicer if I could just destroy the actual flags and not the bases, but that means that the UI stays on screen saying to capture the flags

I have no clue why the old flag spawn stuff wasn't working properly, and this new method could use some more testing tbh

2022-03-29 23:30 UTC, abarichello requested changes

2022-03-29 23:30 UTC, abarichello commented on Northstar.CustomServers/mod/scripts/vscripts/gamemodes/_gamemode_ctf.nut
> +
```suggestion
		//printt("Flags will swap: " + shouldSwap)

```

2022-03-29 23:30 UTC, abarichello commented on Northstar.CustomServers/mod/scripts/vscripts/gamemodes/_gamemode_ctf.nut
> +		//printt("Flag team before: " + flagTeam)
```suggestion
		//printt("Flag team before: " + flagTeam)
```

2022-03-29 23:30 UTC, abarichello commented on Northstar.CustomServers/mod/scripts/vscripts/gamemodes/_gamemode_ctf.nut
> +		//printt("Flag team after: " + flagTeam)
```suggestion
		//printt("Flag team after: " + flagTeam)
```

2022-03-31 20:45 UTC, abarichello approved these changes
Ty

2022-03-31 20:45 UTC, merged

2022-04-02 01:53 UTC, Revadike commented
Does this mean we finally get some good CTF lobbies? 🤞

2022-04-02 10:20 UTC, ASpoonPlaysGames commented
I can't guarantee good, but they should be better