Update sh_titan_embark.gnut to have the arm badge as a client side riff for FP embarks
R2Northstar/NorthstarMods pull request #302
Opened 2022-04-13 12:05 UTC by Gityeeter

Makes the Titan arm badge as a client side riff for toggling FP embarks.

2022-07-01 21:10 UTC, uniboi reviewed
Some small things

2022-07-01 21:10 UTC, uniboi commented on Northstar.Custom/mod/scripts/vscripts/titan/sh_titan_embark.gnut
> +
funny whitespaces in the commit

2022-07-01 21:10 UTC, uniboi commented on Northstar.Custom/mod/scripts/vscripts/titan/sh_titan_embark.gnut
> +	else if((player.GetPetTitan() != null))
`else if((player.GetPetTitan())` might be a bit better to read

2022-07-01 21:10 UTC, uniboi commented on Northstar.Custom/mod/scripts/vscripts/titan/sh_titan_embark.gnut
> +	else if((player.GetPetTitan() != null))
`else if((player.GetPetTitan())` maybe

2022-08-23 20:20 UTC, uniboi commented
Are you still alive?

2022-08-23 20:28 UTC, Gityeeter commented
I was busy with some other stuff with the past couple of months. Is there something i should do?

2022-08-23 20:33 UTC, x3Karma commented
> I was busy with some other stuff with the past couple of months. Is there something i should do?

Honestly, not much, probably just check the suggested changes and maybe follow Northstar formatting if you're available.

2022-10-02 08:21 UTC, uniboi requested changes
Just some more formatting, the rest looks good.

2022-10-02 08:21 UTC, uniboi commented on Northstar.Custom/mod/scripts/vscripts/titan/sh_titan_embark.gnut
> +		if ( !IsValid( soul.soul.armBadge ))
```suggestion
		if ( !IsValid( soul.soul.armBadge ) )
```

2022-10-02 08:21 UTC, uniboi commented on Northstar.Custom/mod/scripts/vscripts/titan/sh_titan_embark.gnut
> +	else if((player.GetPetTitan() != null))
```suggestion
	else if( IsValid( player.GetPetTitan() )
```

2022-10-02 08:21 UTC, uniboi commented on Northstar.Custom/mod/scripts/vscripts/titan/sh_titan_embark.gnut
> +		if ( IsValid( soul.soul.armBadge ))
```suggestion
		if ( IsValid( soul.soul.armBadge ) )
```

2022-10-02 08:21 UTC, uniboi commented on Northstar.Custom/mod/scripts/vscripts/titan/sh_titan_embark.gnut
> +	else if((player.GetPetTitan() != null))
```suggestion
	else if( IsValid( player.GetPetTitan() )
```

2022-10-02 08:21 UTC, uniboi commented on Northstar.Custom/mod/scripts/vscripts/titan/sh_titan_embark.gnut
> +		if ( IsValid( soul.soul.armBadge ))
```suggestion
		if ( IsValid( soul.soul.armBadge ) )
```

2024-05-10 00:04 UTC, closed without merging