change reload mods logic to have weapon reparsing work better on conn…
R2Northstar/NorthstarMods pull request #324
Opened 2022-04-23 23:46 UTC by BobTheBob9

…ect to a server with different enabled mods

2022-07-20 10:14 UTC, EladNLG requested changes
Many unnecessary changes

2022-07-20 10:14 UTC, EladNLG commented on Northstar.Client/mod/scripts/vscripts/ui/menu_ns_serverbrowser.nut
> +const float DOUBLE_CLICK_TIME_MS = 0.4 // unsure what the ideal value is
0.5s is the time used for windows by default.

2022-07-20 10:14 UTC, EladNLG commented on Northstar.Client/mod/scripts/vscripts/ui/menu_ns_serverbrowser.nut
> +	if ( arg1 > arg2 - tolerance && arg1 < arg2 + tolerance) return true
The old version of this function worked just fine? No need to change it...

2022-07-20 10:14 UTC, EladNLG commented on Northstar.Client/mod/scripts/vscripts/ui/menu_ns_serverbrowser.nut
> +	file.scrollOffset = -int( ( (newPos - minYPos) / useableSpace ) * (file.serversArrayFiltered.len() - 15) )
Use BUTTONS_PER_PAGE.

2022-07-20 10:14 UTC, EladNLG commented on Northstar.Client/mod/scripts/vscripts/ui/menu_ns_serverbrowser.nut
> +	float height = maxHeight * (15.0 / servers )
Same issue here.

2022-07-20 10:14 UTC, EladNLG commented on Northstar.Client/mod/scripts/vscripts/ui/menu_ns_serverbrowser.nut
> +	if (file.serversArrayFiltered.len() <= 15) return
And here.

2022-08-07 17:12 UTC, BobTheBob9 commented
this sucks atm and should be done in native code, not script

2022-08-07 17:12 UTC, closed without merging