(maybe) fixed respawn crash exploit
R2Northstar/NorthstarMods pull request #343
Opened 2022-05-05 11:49 UTC by ScureX

currently a certain someone is going around crashing servers by getting the game to try and respawn them when theyre still alive. This might fix it, based on the logs (modified for simplicity):
```
[info] [SERVER SCRIPT] SCRIPT ERROR: [SERVER] Player is already alive.
[info] [SERVER SCRIPT]  -> this.Code_RespawnPlayer( ent )
*FUNCTION [CPlayer()] class/CPlayer.nut line [72]
*FUNCTION [RespawnAsPilot()] mp/_base_gametype_mp.gnut line [423]
*FUNCTION [CodeCallback_OnClientConnectionCompleted()] mp/_base_gametype_mp.gnut line [177]
```
If you need full logs dm me on discord. In both crashes this was the log so i hope this pr fixes it

2022-05-05 12:22 UTC, GeckoEidechse commented
Looks sensible to me. Tagging @RoyalBlue1 to take a look as well, cause your understanding of Mods codebase and Squirrel is a lot better than mine ^^

2022-05-05 12:28 UTC, GeckoEidechse commented
In the end this is more of a hotfix rather than solving the underlying issue but if it remedies the current situation I'm fine with merging it.

2022-05-05 13:09 UTC, ScureX commented
Alright so i also added an IsValid check before the IsAlive check. 
Wolf figured out that he apparently connects, which makes him alive, then fake reconnects so the server tries to make him alive again which is already the case tho.
basically: 
` connects -> sever makes alive -> tells server hes not connected -> fake connects again -> server tries to set alive again`
i suspect the next thing he tries would be fake connecting and making himself invalid somehow so i added those extra checks. nothing confirmed, but we believe this is whats happening so the pr should fix it.

2022-05-05 13:49 UTC, RoyalBlue1 requested changes

2022-05-05 13:49 UTC, RoyalBlue1 commented on Northstar.CustomServers/mod/scripts/vscripts/mp/_base_gametype_mp.gnut
> +	if(IsValid( player )) return
the IsValid check is not needed as IsAlive returns false when the entity is not valid. also it might block legit respawns

2022-05-05 13:49 UTC, RoyalBlue1 commented on Northstar.CustomServers/mod/scripts/vscripts/mp/_base_gametype_mp.gnut
> +	if(IsValid( player )) return
same as above

2022-05-05 14:35 UTC, ScureX commented
didnt know that IsAlive handles that, removed it again.

2022-05-13 22:43 UTC, RoyalBlue1 approved these changes

2022-07-10 15:33 UTC, BobTheBob9 commented
closing as this is fixed in launcher atm https://github.com/R2Northstar/NorthstarLauncher/commit/c64a0d148f5fcfe7fee50dcc6414348143898ab6

2022-07-25 13:46 UTC, fvnkhead commented
Hi, I'm running 1.9.2 but still got the same crash @ScureX :

```
[13:35:01] [info] [SERVER SCRIPT] SCRIPT ERROR: [SERVER] Player is already alive.
[13:35:01] [info] [SERVER SCRIPT]  -> this.Code_RespawnPlayer( ent )
[13:35:01] [info] [SERVER SCRIPT]
CALLSTACK
*FUNCTION [CPlayer()] class/CPlayer.nut line [72]
*FUNCTION [RespawnAsPilot()] mp/_base_gametype_mp.gnut line [427]
*FUNCTION [CodeCallback_OnClientConnectionCompleted()] mp/_base_gametype_mp.gnut line [181]

[13:35:01] [info] [SERVER SCRIPT] LOCALS
[ent] ENTITY (info_spawnpoint_human [0] at <-2092.67 2446.84 148.784>)
[this] ENTITY (player StinkyTheSquid2 [11] (player "StinkyTheSquid2" at <3352.84 -4.09219 344.031>))
[player] ENTITY (player StinkyTheSquid2 [11] (player "StinkyTheSquid2" at <3352.84 -4.09219 344.031>))
[this] TABLE
[skycam] ENTITY (sky_camera skybox_cam_level [140] at <-5688 7112 -4544>)
[player] ENTITY (player StinkyTheSquid2 [11] (player "StinkyTheSquid2" at <3352.84 -4.09219 344.031>))
[this] TABLE
```

This same person (spoofed name) tried to DoS before, but failed.

2022-07-25 14:05 UTC, GeckoEidechse commented
Hmm, maybe we should re-open this, @BobTheBob9? ^^

2022-07-25 14:06 UTC, GeckoEidechse commented on Northstar.CustomServers/mod/scripts/vscripts/mp/_base_gametype_mp.gnut
> +	if(IsAlive( player )) return
Maybe add a comment to both functions so that it's clear for someone going over the script in the future that this is a hotfix?

2022-07-25 16:00 UTC, fvnkhead commented
I added some logging on client connect and confirmed that this was done by triggering a fake reconnect on another (trusted) player who was alive

2022-07-25 16:15 UTC, fvnkhead commented
Nevermind @GeckoEidechse , I thought this fix was in 1.9.2 but apparently not 🤦 sorry for the trouble

2022-07-25 19:46 UTC, GeckoEidechse commented
> I added some logging on client connect and confirmed that this was done by triggering a fake reconnect on another (trusted) player who was alive

Thanks for the heads-up we might wanna further look into that. Feel free to DM me if you find anything else of interest ^^

2022-08-03 19:36 UTC, GeckoEidechse commented
Re-opening cause the underlying issue has not been fixed it seems.

2022-08-25 10:59 UTC, H0L0theBard commented
I would just like to mention that Takyon has merged the funny minecraft font into this pr :trollface:

2022-08-25 11:00 UTC, GeckoEidechse commented
> I would just like to mention that Takyon has merged the funny minecraft font into this pr :trollface:

omfg @ScureX why? x_x

2022-08-25 11:07 UTC, GeckoEidechse requested changes

2022-08-25 11:07 UTC, GeckoEidechse commented on Northstar.Custom/mod/resource/fontfiletable.txt
> +FontFileTable
Please remove >:(

2022-08-25 11:10 UTC, H0L0theBard commented on Northstar.Custom/mod/resource/fontfiletable.txt
> +FontFileTable
:trollface:

2022-08-25 23:29 UTC, GeckoEidechse commented
Superseded by #491

2022-08-25 23:29 UTC, closed without merging