fixing peacekraber in sp ( again )
R2Northstar/NorthstarMods pull request #398
Opened 2022-06-18 21:42 UTC by catornot

the previous pr ( #382 ) didn't work for everyone. this time it should.
[https://canary.discord.com/channels/920776187884732556/987319483846778890/987459128878313513](https://canary.discord.com/channels/920776187884732556/987319483846778890/987459128878313513)

2022-07-12 03:33 UTC, ASpoonPlaysGames approved these changes
Whether or not this does fix the issue in SP or if there are more issues doesn't really matter, peacekraber should be enabled on both MP and SP, no reason not to.

2022-07-20 10:09 UTC, EladNLG approved these changes

2022-07-21 23:28 UTC, GeckoEidechse requested changes
Uh, so even with the PR I still cannot do `give mp_weapon_peacekraber` in Singleplayer campaign when I tested.

2022-07-21 23:29 UTC, catornot commented
yeah because you need to precache it.

2022-08-07 23:09 UTC, GeckoEidechse approved these changes

2022-10-07 20:08 UTC, ASpoonPlaysGames commented
Anything blocking this from being merged?

2022-12-03 16:28 UTC, uniboi commented
@catornot update your branch

2022-12-03 16:31 UTC, catornot commented
oh no I merged co-op

2022-12-03 16:43 UTC, catornot commented
huh should have fixed idk

2022-12-03 17:46 UTC, uniboi commented
you need to merge main into sp-fix2

2022-12-03 20:28 UTC, catornot commented
😅

2022-12-04 11:51 UTC, uniboi approved these changes
![image](https://user-images.githubusercontent.com/64006268/205488768-f62c1f4d-f59e-4b04-af9c-47c6f0cb3d4a.png)
works in both mp and sp, code is good

2022-12-04 11:52 UTC, uniboi commented on Northstar.Custom/mod.json
> +			"RunOn": "( CLIENT || SERVER )"
```suggestion
			"RunOn": "CLIENT || SERVER"
```

to keep style of the other context conditions

2022-12-12 19:56 UTC, GeckoEidechse commented
> damn this is a lot of commit history for a single line change

And I cannot even test it atm cause I cannot launch SP without `Invalid Name` error xD

2022-12-12 20:02 UTC, uniboi commented
> > damn this is a lot of commit history for a single line change
> 
> And I cannot even test it atm cause I cannot launch SP without `Invalid Name` error xD

allow insecure auth in customservers autoexec.cfg

2023-01-18 10:18 UTC, uniboi commented
@GeckoEidechse did you manage to test yet?

2023-01-22 22:51 UTC, ASpoonPlaysGames requested changes
Technically speaking this works in testing, the peacekraber can be acquired in SP. However, `sh_northstar_custom_precache` is not ran on SP, which means that the peacekraber is not precached, meaning you cannot get it without setting `host_thread` to a value other than 1 (0 works) and then precaching it manually via console.

This should probably get fixed

2023-01-22 22:55 UTC, catornot commented
It's supposed to be precached in co-op
[sh_coop_custom_precache.gnut](https://github.com/xamionex/NorthstarMods/blob/co-op/Northstar.Coop/mod/scripts/vscripts/sh_coop_custom_precache.gnut)

2023-01-22 22:56 UTC, ASpoonPlaysGames commented
> 

sure, but that's not fixing the peacekraber in SP, that's fixing it in coop. The peacekraber remains in a broken state in normal SP

2023-01-22 22:58 UTC, ASpoonPlaysGames commented
Btw from my own testing just now, just running `sh_northstar_custom_precache` on `CLIENT || SERVER` works just fine with no noticeable side effects in normal SP (triple threat works, as does the peacekraber)
If there are errors from running it with coop, then maybe remove the precaching on coop?

2023-01-22 23:34 UTC, catornot commented
making `sh_northstar_custom_precache ` `CLIENT || SERVER` wasn't working for some people, weird stuff `¯\_(ツ)_/¯`

2023-04-14 13:38 UTC, closed without merging