dont remove amped weapons after entering titan
R2Northstar/NorthstarMods pull request #432
Opened 2022-07-17 23:00 UTC by BobTheBob9

2022-07-17 23:46 UTC, x3Karma commented
Other than the misspelling looks good to ms

2022-07-18 00:20 UTC, GeckoEidechse commented
> Other than the misspelling looks good to ms

Which to be precise? ^^

2022-07-18 00:33 UTC, x3Karma commented on Northstar.CustomServers/mod/scripts/vscripts/burnmeter/_burnmeter.gnut
> +void function InitialisePermenantAmpedWeaponsForPlayer( entity player )
```suggestion
void function InitialisePermanentAmpedWeaponsForPlayer( entity player )
```

2022-07-18 00:33 UTC, x3Karma commented on Northstar.CustomServers/mod/scripts/vscripts/burnmeter/_burnmeter.gnut
> +	player.s.hasPermenantAmpedWeapons <- false
```suggestion
	player.s.hasPermanentAmpedWeapons <- false
```

2022-07-18 00:35 UTC, RoyalBlue1 commented
this crashes during compile in EarnMeterMP_BoostEarned with incorrect amount of parameters. fixing the amount of parameters will revert #313

2022-07-18 14:09 UTC, RoyalBlue1 commented
Also there should probably be a death callback that resets hasPermanentAmpedWeapons to false

2022-07-18 16:05 UTC, RoyalBlue1 commented
> Would this work for the following scenario?
> 
> 1. Player gets permanent amped weapons
> 2. Player swaps out one or more of their weapons
> 3. Player enters titan
> 4. Player exits titan
> 5. Only the guns that the player had originally have amped weapons

this works as intended

2022-07-21 23:35 UTC, GeckoEidechse requested changes
Marking as changes requested based on @RoyalBlue1 comment: https://github.com/R2Northstar/NorthstarMods/pull/432#issuecomment-1186644671

2024-08-14 15:31 UTC, GeckoEidechse commented
bump lol

2024-08-14 20:46 UTC, Zanieon commented
I think this is actually safe to close because:

1. Permanent Amped Weapons is an exclusive boost to Frontier Defense
2. @RoyalBlue1 Already integrated this PR in the Frontier Defense branch even before i assumed development of it
3. Due to both above this will automatically come along together when Frontier Defense is officially merged into main

2024-08-14 20:46 UTC, closed without merging