Serverside RUI, but it doesn't stink ( hopefully )
R2Northstar/NorthstarMods pull request #435
Opened 2022-07-19 14:53 UTC by F1F7Y

Allows servers to use rui presets on clients, clients dont need to update to play

# Polls
```cpp
void function NSCreatePollOnPlayer( entity player, string header, array<string> options, float duration );
int function NSGetPlayerResponse( entity player );
```
![poll-image](https://user-images.githubusercontent.com/64418963/179780783-823e22ad-ed0f-4da3-9f65-c0e3f97a717a.png)

# Large message
```cpp
void function NSSendLargeMessageToPlayer( entity player, string title, string description, float duration, string image );
```
![large](https://user-images.githubusercontent.com/64418963/173656741-e87de1f7-3eb6-407f-b351-ad8cdbe7e6b8.gif)

# Info
```cpp
void function NSSendInfoMessageToPlayer( entity player, string text );
```
![info](https://user-images.githubusercontent.com/64418963/173657176-f5625116-6723-4d95-84f5-a7adfdda0a40.gif)

# PopUp
```cpp
void function NSSendPopUpMessageToPlayer( entity player, string text );
```
![popup](https://user-images.githubusercontent.com/64418963/173656795-1b4caf01-58da-4bd5-9332-c8b55848793a.gif)

# Announcement
```cpp
void function NSSendAnnouncementMessageToPlayer( entity player, string title, string description, vector color, int priority, int style );
```
![announcement](https://user-images.githubusercontent.com/64418963/173828411-5c363ea2-3810-433c-86b5-48520ed69e41.gif)

# Status
```cpp
void function NSCreateStatusMessageOnPlayer( entity player, string title, string description, string id );
void function NSEditStatusMessageOnPlayer( entity player, string title, string description, string id  );
void function NSDeleteStatusMessageOnPlayer( entity player, string id  );
```
![2status](https://user-images.githubusercontent.com/64418963/173828784-9ccbc0c8-ddc6-4071-be10-d0f65819df39.gif)

2022-07-19 18:42 UTC, GeckoEidechse commented on Northstar.Custom/mod/scripts/vscripts/sh_message_utils.gnut
> +		// Remove it form table
Typo? ^^

```suggestion
		// Remove it from table
```

2022-07-19 18:42 UTC, uniboi approved these changes
[Odd.RuiDemo.zip](https://github.com/R2Northstar/NorthstarMods/files/9143832/Odd.RuiDemo.zip)

Code looks fine and tested all features hud elements, looks good to me!

2022-07-19 18:44 UTC, F1F7Y commented on Northstar.Custom/mod/scripts/vscripts/sh_message_utils.gnut
> +		// Remove it form table
:)

2022-07-21 23:44 UTC, GeckoEidechse approved these changes
Worked fine in testing

(many thanks to @uniboi for the demo mod <3)

2022-07-22 00:15 UTC, RoyalBlue1 reviewed
The spaces between the numbers and the bracket are not always in Respawn code but Gecko wants them to be there. The ones between the numbers themselves are always there.

Pls fix this as a batch commit

2022-07-22 00:15 UTC, RoyalBlue1 commented on Northstar.Custom/mod/scripts/vscripts/sh_message_utils.gnut
> +		RuiSetFloat3( rui, "bgColor", <0,0,0> )
```suggestion
		RuiSetFloat3( rui, "bgColor", < 0, 0, 0 > )
```

2022-07-22 00:15 UTC, RoyalBlue1 commented on Northstar.Custom/mod/scripts/vscripts/sh_message_utils.gnut
> +		RuiSetFloat2( rui, "msgPos", <0, 0.4 + i * 0.025, 0> )
```suggestion
		RuiSetFloat2( rui, "msgPos", < 0, 0.4 + i * 0.025, 0 > )
```

2022-07-22 00:15 UTC, RoyalBlue1 commented on Northstar.Custom/mod/scripts/vscripts/sh_message_utils.gnut
> +	RuiSetFloat2( rui, "offset", <0,-250,0> )
```suggestion
	RuiSetFloat2( rui, "offset", < 0, -250, 0 > )
```

2022-07-22 00:15 UTC, RoyalBlue1 commented on Northstar.Custom/mod/scripts/vscripts/sh_message_utils.gnut
> +vector ColorBase = <0.9, 0.5, 0.1>
```suggestion
vector ColorSelected = < 0.9, 0.8, 0.5 >
vector ColorBase = < 0.9, 0.5, 0.1 >
```

2022-07-22 00:44 UTC, ScureX requested changes

2022-07-22 00:44 UTC, ScureX commented on Northstar.Custom/mod/scripts/vscripts/sh_message_utils.gnut
> +} client
```suggestion
	table<string,var> statusMessageList
} client
```
hate new lines

2022-07-22 00:44 UTC, ScureX commented on Northstar.Custom/mod/scripts/vscripts/sh_message_utils.gnut
> +			i++
```suggestion
			RuiSetInt( _rui, "listPos", i )
			i++
```
looks ugly idk

2022-07-22 00:44 UTC, ScureX commented on Northstar.Custom/mod/scripts/vscripts/sh_message_utils.gnut
> +	for( int i = 0; i < client.poll.options.len() + 1; i++ )
```suggestion
	client.poll.pollActive = true
	
	for( int i = 0; i < client.poll.options.len() + 1; i++ )
```
do you like new lines or sumn, one is enough

2022-07-22 00:44 UTC, ScureX commented on Northstar.Custom/mod/scripts/vscripts/sh_message_utils.gnut
> +		//RuiSetInt( rui, "lineNum", i )
```suggestion
```
dont need those comments do we? if you want those as a guide on how shit works maybe make it comprehensive n stuff

2022-07-22 00:44 UTC, ScureX commented on Northstar.Custom/mod/scripts/vscripts/sh_message_utils.gnut
> +
```suggestion
	
```
newline my beloved

2022-07-22 00:44 UTC, ScureX commented on Northstar.Custom/mod/scripts/vscripts/sh_message_utils.gnut
> +		wait 7
should make this a constant, convar or able to set within the command that calls this function. just waiting however long you think is nice might fuck you over in the future

2022-07-22 00:44 UTC, ScureX commented on Northstar.Custom/mod/scripts/vscripts/sh_message_utils.gnut
> +		wait 5
should make this a constant, convar or able to set within the command that calls this function. just waiting however long you think is nice might fuck you over in the future

2022-07-22 00:44 UTC, ScureX commented on Northstar.Custom/mod/scripts/vscripts/sh_message_utils.gnut
> +		wait 2.4
should make this a constant, convar or able to set within the command that calls this function. just waiting however long you think is nice might fuck you over in the future

2022-07-22 00:44 UTC, ScureX commented on Northstar.Custom/mod/scripts/vscripts/sh_message_utils.gnut
> +		client.infoMessageQueue.remove(0)
```suggestion
		client.infoMessageQueue.remove( 0 )
```
we do the shitty spaces everywhere so why not here?

2022-07-22 00:44 UTC, ScureX commented on Northstar.Custom/mod/scripts/vscripts/sh_message_utils.gnut
> +#endif // CLIENT
```suggestion
}
#endif // CLIENT
```

we didnt add a new line after the \#if SERVER so why add one before the \#endif

2022-07-23 13:24 UTC, F1F7Y commented
Me when firefox cached the page and I didn't see the reviews :)

2022-07-23 13:40 UTC, uniboi commented
> The spaces between the numbers and the bracket are not always in Respawn code but Gecko wants them to be there. The ones between the numbers themselves are always there.
> 
> Pls fix this as a batch commit

this worsens readability and I've seen respawn formatting vectors as `<x, y, z>` more often than `< x, y, z >`

2022-07-23 13:41 UTC, ASpoonPlaysGames commented
> > The spaces between the numbers and the bracket are not always in Respawn code but Gecko wants them to be there. The ones between the numbers themselves are always there.
> > Pls fix this as a batch commit
> 
> this worsens readability and I've seen respawn formatting vectors as `<x, y, z>` more often than `< x, y, z >`

Counterpoint: `<x, y, z>` creates a compile error if x is negative so i prefer the other option

2022-07-23 13:49 UTC, uniboi commented
ok I changed my mind I just used `<(x), y z>` for no reason whatsoever when a better option exists

2022-07-23 13:50 UTC, F1F7Y commented
> 

you can also `vector(x, y, z)` iirc

2022-07-25 15:01 UTC, GeckoEidechse commented
Someone giving the suggested changes a final look and test maybe would be appreciated <3

2022-07-26 08:56 UTC, uniboi commented
> Someone giving the suggested changes a final look and test maybe would be appreciated <3

What changes are you referring to? I thought only formatting has been changed so the test mod I sent earlier should still work fine?

2022-07-26 13:37 UTC, GeckoEidechse commented
> > Someone giving the suggested changes a final look and test maybe would be appreciated <3
> 
> What changes are you referring to? I thought only formatting has been changed so the test mod I sent earlier should still work fine?

The commits that were added since the last review basically. I think it was just formatting as you said (don't have the setup rn to check). For testing, just running newest version of PR with your mod again should be enough. It's just to make sure there weren't any accidental errors syntax or whatever added since last change. Usually I'd do this myself but I'm on holiday atm :P

2022-07-26 15:13 UTC, GeckoEidechse commented
> ![image](https://user-images.githubusercontent.com/64006268/181039296-2840c7c7-8c37-438a-90be-b99ca62561a1.png) @GeckoEidechse everything works now and images are fixed. This is imo ready to merge

Aight, Imma put my trust in you :P

Time to merge :D

2022-07-26 15:16 UTC, merged

2022-07-26 15:17 UTC, GeckoEidechse commented
Welp, it's been fun not having to cherry-pick commits for patch releases ._.

2022-07-26 16:34 UTC, x3Karma commented
WOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO