Fix missing fonts under Linux
R2Northstar/NorthstarMods pull request #437
Opened 2022-07-20 06:30 UTC by KyleGospo

This PR replaces Arial with Lato, and Lucidia with Source Code Pro, removing the need to install fonts when running the game on Linux. Licenses for these fonts have been included along-side the TTF.

2022-07-20 14:28 UTC, KyleGospo commented
Arial & Lucidia Console:
![ArialLucidia](https://user-images.githubusercontent.com/10704358/180007666-e264226d-f3ea-40b8-b608-a298df7483bd.png)

Lato & Source Code Pro:
![LatoSCP](https://user-images.githubusercontent.com/10704358/180007688-583c9cbe-224f-4e19-8f74-37747d189520.png)

2022-07-20 23:50 UTC, GeckoEidechse requested changes
(Sadly) quick Discord poll said no to `Fira code` ;-;
![](https://cdn.discordapp.com/attachments/972909610140839956/999462913444155392/unknown.png)

Consolas was a suggested alternative

2022-07-21 01:02 UTC, GeckoEidechse commented
An issue we also noticed in testing that streaming the in-game console with `Fira Code` from a 1440p screen to a 1080p via Discord on Text readability mode, rendered the text unreadable on the 1080p screen. So it should be big enough for it to be still readable like the current version is. ^^

2022-07-21 04:25 UTC, KyleGospo commented
> An issue we also noticed in testing that streaming the in-game console with `Fira Code` from a 1440p screen to a 1080p via Discord on Text readability mode, rendered the text unreadable on the 1080p screen. So it should be big enough for it to be still readable like the current version is. ^^

Created a custom font to solve this. Meet Fira Mono Northstar:
![FiraNorthstar](https://user-images.githubusercontent.com/10704358/180129575-38bdef58-3868-49fb-aeb2-0b90dc4d0773.png)

2022-07-21 22:33 UTC, GeckoEidechse commented on Northstar.Client/mod/resource/fontfiletable.txt
> +	// Everything below is DONOTSHIP / Dev only
Uh, is this still relevant?

2022-07-21 22:35 UTC, GeckoEidechse commented on Northstar.Client/mod/resource/fontfiletable.txt
> +	// Everything below is DONOTSHIP / Dev only
Turns out that comment was added by Respawn in the original file inside the VPK :,)

2022-07-21 22:37 UTC, GeckoEidechse approved these changes
Got enough positive feedback on the updated font to consider it mergeable ^^

2022-07-21 22:38 UTC, merged