Refuse noclipping while player is setparented
R2Northstar/NorthstarMods pull request #487
Opened 2022-08-21 18:01 UTC by DBmaoha

change movetype while setparented will crush the server

2022-08-21 23:49 UTC, uniboi requested changes

2022-08-21 23:49 UTC, uniboi commented on Northstar.CustomServers/mod/scripts/vscripts/_northstar_cheatcommands.nut
> +	if( player.GetParent() != null ) // change movetype while setparented will crush the server
```suggestion
	if( !player.GetParent() ) // change movetype while setparented will crush the server
```

2022-09-21 07:08 UTC, uniboi requested changes

2022-09-21 07:08 UTC, uniboi commented on Northstar.CustomServers/mod/scripts/vscripts/_northstar_cheatcommands.nut
> +		return true
```suggestion
{
		print( player + " failed noclipping because the entity is parented" )
		return true
}
```
Log some info to avoid confusion

2022-09-21 10:39 UTC, GeckoEidechse commented on Northstar.CustomServers/mod/scripts/vscripts/_northstar_cheatcommands.nut
> +	if( player.GetParent() ) // change movetype while setparented will crush the server
```suggestion
	if( player.GetParent() ) // change movetype while setparented will crash the server
```

typo :P

2022-09-24 13:29 UTC, uniboi approved these changes
I didn't test but I used my braincells to conclude that literally nothing can go wrong

2022-09-24 23:38 UTC, emma-miler approved these changes

2022-09-24 23:47 UTC, GeckoEidechse approved these changes
Works in testing.

2022-09-24 23:48 UTC, merged