Fixed Phase Rewind not Behaving Well
R2Northstar/NorthstarMods pull request #505
Opened 2022-09-17 21:08 UTC by DBmaoha

Phase Rewind will now have a longer distance and mostly won't stuck as It be like in vanilla
Map Hack won't show sonar pulse to other players anymore, also be like in vanilla

2022-09-22 16:18 UTC, uniboi approved these changes
https://user-images.githubusercontent.com/64006268/191799273-c78f5b28-1a8f-430c-8917-d221b31172c6.mp4

I think this mimics vanilla perfectly
https://user-images.githubusercontent.com/64006268/191799318-d15f52f2-942f-4800-b5a3-38f063a3c055.mp4

2022-09-22 16:36 UTC, Erlite commented
Do you have a video to compare before your PR? Just curious what the difference is.

2022-09-22 16:48 UTC, uniboi commented
look at the filenames lmao the first on is vanilla the second one is from the pr

2022-09-22 16:49 UTC, Erlite commented
No I mean in Northstar before your PR, unless that's what Vanilla is?

2022-09-22 16:56 UTC, uniboi commented
https://user-images.githubusercontent.com/64006268/191807056-96957802-aa6a-4285-9016-1a626bc3b478.mp4

there's a notable difference to the state phase rewind is currently in northstar

2022-09-22 16:56 UTC, Erlite commented
Awesome work!

2022-09-22 18:14 UTC, ASpoonPlaysGames requested changes
Formatting things + removing now-unneeded lines

2022-09-22 18:14 UTC, ASpoonPlaysGames commented on Northstar.CustomServers/mod/scripts/vscripts/burnmeter/_burnmeter.gnut
> +    return PutPhaseRewindedPlayerInSafeSpot( player, severity+5 )
```suggestion
	if ( PutEntityInSafeSpot( player, player, null, < baseOrigin.x, baseOrigin.y + severity, baseOrigin.z >, baseOrigin ) )
		return

	if ( PutEntityInSafeSpot( player, player, null, < baseOrigin.x, baseOrigin.y - severity, baseOrigin.z >, baseOrigin ) )
		return

	if ( PutEntityInSafeSpot( player, player, null, < baseOrigin.x + severity, baseOrigin.y, baseOrigin.z >, baseOrigin ) )
		return

	if ( PutEntityInSafeSpot( player, player, null, < baseOrigin.x - severity, baseOrigin.y, baseOrigin.z >, baseOrigin ) )
        	return

	if ( PutEntityInSafeSpot( player, player, null, < baseOrigin.x, baseOrigin.y, baseOrigin.z + severity >, baseOrigin ) )
		return

	if ( PutEntityInSafeSpot( player, player, null, < baseOrigin.x, baseOrigin.y, baseOrigin.z - severity >, baseOrigin ) )
		return

	return PutPhaseRewindedPlayerInSafeSpot( player, severity + 5 )

```
formatting things

2022-09-22 18:14 UTC, ASpoonPlaysGames commented on Northstar.CustomServers/mod/scripts/vscripts/burnmeter/_burnmeter.gnut
> +		player.SetOrigin( player.GetOrigin() + < 0,0,20 > )
```suggestion
		player.SetOrigin( player.GetOrigin() + < 0, 0, 20 > )
```

2022-09-22 18:14 UTC, ASpoonPlaysGames commented on Northstar.CustomServers/mod/scripts/vscripts/burnmeter/_burnmeter.gnut
> +		//	moveTime = PHASE_REWIND_PATH_SNAPSHOT_INTERVAL
```suggestion
```
Can probably remove these lines

2022-09-22 18:14 UTC, ASpoonPlaysGames commented on Northstar.CustomServers/mod/scripts/vscripts/burnmeter/_burnmeter.gnut
> +		//print( positions[ i ].origin )
```suggestion
```
Debug print can probably be removed

2022-09-26 23:42 UTC, GeckoEidechse commented
@uniboi do you wanna retest after new changes, in particular 136a75f9e40668249dd38f6c21cb505259569a27 ?

Code formatting looks fine from what I can tell, so assuming @ASpoonPlaysGames did code (logic) review we could merge it after testing. ^^

2022-09-27 19:57 UTC, uniboi commented
https://user-images.githubusercontent.com/64006268/192623180-ef856b6e-8010-4fcf-8e58-55925cc674ad.mp4

2022-09-27 20:12 UTC, merged