feat: Add missing translations
R2Northstar/NorthstarMods pull request #508
Opened 2022-09-20 17:02 UTC by Alystrasz

Adds missing Chinese, French, German, Italian and Spanish translation entries.

Thanks to @GeckoEidechse, `Cloud__#0920`, `wolf109909#5291` and `DumbAndre#5622` for their help.

2022-09-21 11:14 UTC, uniboi requested changes

2022-09-21 11:14 UTC, uniboi commented on Northstar.Client/mod/resource/northstar_client_localisation_german.txt
> +		"AUTHENTICATIONAGREEMENT_NO" "Du hast dich entschieden dich nicht mit Northstar zu authentizifieren. Du kannst die Authentifizierungs-Einwilligung im Modmenü ansehen."
```suggestion
		"AUTHENTICATIONAGREEMENT_NO" "Du hast dich gegen die Authentifizierung mit Northstar entschieden. Du kannst die Authentifizierungs-Einwilligung im Modmenü ansehen."
		Sounds better
```

2022-09-21 11:14 UTC, uniboi commented on Northstar.Client/mod/resource/northstar_client_localisation_german.txt
> +		"PL_sns_abbr" "SuS"
💀

2022-09-21 11:14 UTC, uniboi commented on Northstar.Client/mod/resource/northstar_client_localisation_german.txt
> +		"HIDE_LOCKED" "Verstecke geperrte"
```suggestion
		"HIDE_LOCKED" "Verstecke gesperrte"
```

2022-09-21 11:24 UTC, F1F7Y commented on Northstar.Client/mod/resource/northstar_client_localisation_german.txt
> +		"PL_sns_abbr" "SuS"
sus

2022-09-21 11:27 UTC, Alystrasz commented on Northstar.Client/mod/resource/northstar_client_localisation_german.txt
> +		"PL_sns_abbr" "SuS"
oh my

2022-09-25 23:07 UTC, GeckoEidechse commented
I assume I can merge this or is there anything you wanna update still? ^^

2022-09-26 09:15 UTC, Alystrasz commented
Yep you can merge this, I don't expect other translations to be added.

2022-09-26 11:31 UTC, merged