Fix server crash from demigod setting health over max health.
R2Northstar/NorthstarMods pull request #509
Opened 2022-09-20 22:54 UTC by Erlite

```squirrel
[22:31:22] [info] [SERVER SCRIPT] pilot weapon3 skin/camo 1 81
[22:31:22] [info] [SERVER SCRIPT] SCRIPT ERROR: [SERVER] SetHealth: Can't set health on entity to 6, max health is 1.
[22:31:22] [info] [SERVER SCRIPT]  -> ent.SetHealth( bottomLimit + 1 ) //Set it up so that you at least take 1 damage, for hit indicators etc to trigger
[22:31:22] [info] [SERVER SCRIPT]
CALLSTACK
*FUNCTION [EntityDemigod_TryAdjustDamageInfo()] _utility.gnut line [2131]
*FUNCTION [Wallrun_PlayerTookDamage()] pilot/class_wallrun.gnut line [54]
*FUNCTION [PlayerTookDamage()] mp/_codecallbacks.gnut line [754]
*FUNCTION [CodeCallback_DamagePlayerOrNPC()] mp/_codecallbacks.gnut line [300]
```

2022-09-21 11:01 UTC, uniboi requested changes

2022-09-21 11:01 UTC, uniboi commented on Northstar.CustomServers/mod/scripts/vscripts/_utility.gnut
> +		ent.SetHealth( newHealth )
```suggestion
		ent.SetHealth( ent.GetMaxHealth() < newHealth ? ent.GetMaxHealth() : newHealth )
```
Incredible optimization

2022-09-21 11:04 UTC, Erlite commented
Fair enough.

2022-09-21 11:06 UTC, uniboi approved these changes
Incredibly optimized

2022-09-21 11:13 UTC, Erlite commented
Such speed, very fast

2022-09-22 15:38 UTC, ASpoonPlaysGames requested changes
Looks good except for this formatting

2022-09-22 15:38 UTC, ASpoonPlaysGames commented on Northstar.CustomServers/mod/scripts/vscripts/_utility.gnut
> +	//Set it up so that you at least take 1 damage, for hit indicators etc to trigger
```suggestion
	// Set it up so that you at least take 1 damage, for hit indicators etc to trigger
```

2022-10-03 10:57 UTC, ASpoonPlaysGames approved these changes
Code looks good to me

2022-10-21 18:42 UTC, merged