Fixed Burn Cards Animations
R2Northstar/NorthstarMods pull request #511
Opened 2022-09-24 12:13 UTC by DBmaoha

Burn cards no longer taken right after  using

2022-10-21 18:42 UTC, BobTheBob9 requested changes

2022-10-21 18:42 UTC, BobTheBob9 commented on Northstar.CustomServers/mod/scripts/vscripts/item_inventory/sv_item_inventory.gnut
> +	if( !IsValid( preexistingWeapon ) )
formatting here needs some work, couple newlines around it and it should be good though

2022-11-04 17:42 UTC, uniboi requested changes
Rest looks good

2022-11-04 17:42 UTC, uniboi commented on Northstar.CustomServers/mod/scripts/vscripts/item_inventory/sv_item_inventory.gnut
> +		if( fireTime != null )
```suggestion
		if( fireTime )
```

2022-11-04 17:42 UTC, uniboi commented on Northstar.CustomServers/mod/scripts/vscripts/item_inventory/sv_item_inventory.gnut
> +			thread PlayerInventory_GiveInventoryItem(player, nextInventoryItem)
```suggestion
			thread PlayerInventory_GiveInventoryItem( player, nextInventoryItem )
```

2022-11-12 14:06 UTC, BobTheBob9 approved these changes

2022-11-12 14:06 UTC, merged