Fix server chat messages being send twice when watching a replay
R2Northstar/NorthstarMods pull request #555
Opened 2022-12-22 23:02 UTC by NoCatt

Currently when watching a kill replay, all chat messages that are send from the server to the killer will be shown in the replay.

After this change all messages send will check if the game is currently replaying, and the message will not be send again.
This will avoid issues especially with messages only meant for the killer.

2022-12-22 23:06 UTC, emma-miler requested changes
This isn't actually stopping anything from being sent, only stops the client from showing the message received. Still useful, but not as advertised :P

2022-12-22 23:08 UTC, uniboi approved these changes
better than nothing

previous behaviour:
https://user-images.githubusercontent.com/64006268/209240022-90addfe0-fb56-4a20-8164-eb923ad5948c.mp4

new behaviour:
https://user-images.githubusercontent.com/64006268/209240031-29b31b5c-2caa-44f9-88c3-717d8a2f3f9f.mp4

2022-12-22 23:10 UTC, NoCatt commented
> This isn't actually stopping anything from being sent, only stops the client from showing the message received. Still useful, but not as advertised :P

fixed :)
(I meant send to chat not send at all but its more clear now^^)

2022-12-22 23:11 UTC, emma-miler approved these changes

2022-12-23 03:32 UTC, cpdt commented
Won’t this also prevent normal chat messages sent during replay from being received?

2022-12-23 03:35 UTC, ASpoonPlaysGames requested changes
> Won’t this also prevent normal chat messages sent during replay from being received?

Yes, which would result in the player missing messages entirely. Imo this is worse than receiving duplicate messages, so I have to disapprove of this PR for now

2022-12-23 03:36 UTC, NoCatt commented
> > Won’t this also prevent normal chat messages sent during replay from being received?
> 
> Yes, which would result in the player missing messages entirely. Imo this is worse than receiving duplicate messages, so I have to disapprove of this PR for now

That is already the case though

We specifically checked that

2022-12-23 03:45 UTC, ASpoonPlaysGames commented
> > > Won’t this also prevent normal chat messages sent during replay from being received?
> > 
> > 
> > Yes, which would result in the player missing messages entirely. Imo this is worse than receiving duplicate messages, so I have to disapprove of this PR for now
> 
> That is already the case though
> 
> We specifically checked that
> 
> So effectively nothing changes, but the double messages

Alright then, nevermind. Still I think that we should figure out how vanilla solves this problem, but this will do for now then

2022-12-23 03:48 UTC, cpdt approved these changes
LGTM then, thanks for clarifying.

2022-12-30 21:09 UTC, ASpoonPlaysGames approved these changes
This is a good enough temporary fix, eventually we really should get a better system for this though

2023-01-02 13:18 UTC, Erlite requested changes

2023-01-02 13:18 UTC, Erlite commented on Northstar.Client/mod/scripts/vscripts/_custom_codecallbacks_client.gnut
> +    if( IsWatchingReplay() )
Missing a space after `if`

2023-01-02 16:52 UTC, NoCatt commented on Northstar.Client/mod/scripts/vscripts/_custom_codecallbacks_client.gnut
> +    if( IsWatchingReplay() )
done

2023-01-02 22:11 UTC, Erlite approved these changes
Looks good to me, merge when ready. Bandaid that can be improved later in native.

2023-01-08 01:39 UTC, BobTheBob9 approved these changes
echoing same statements as previous reviewers, should work for now but needs changing later

2023-01-08 01:40 UTC, merged