Clean Team Score After Player Disconneting in FFA
R2Northstar/NorthstarMods pull request #589
Opened 2023-02-03 13:30 UTC by DBmaoha

https://github.com/R2Northstar/NorthstarMods/issues/400
Player's team score will be cleaned after they disconnecting, so later joiners won't have trouble start from 0 score

2023-02-19 18:57 UTC, NoCatt requested changes
The code seems a little too complicated for what this can do.
If we already have a table of the score of each player, wouldnt it also make sense to then save that score so if they re-join they get to keep their score.

Also a better way to do this, is to just save the score of a player in a ``table < string, int > ``. We dont need the struct anyway as the team is unique to each player. 
I would suggest to just add a callback for player disconnect like this:
```
void function OnPlayerDisconnected(entity player)
{
	ffaPlayerScoreTable[player.GetUID()] <- GameRules_GetTeamScore( player.GetTeam() )

	// this prevents a new player to get someone who's left's score
	AddTeamScore( player.GetTeam(), -GameRules_GetTeamScore( player.GetTeam() ))

}
```
That way we can also eliminate the change to the ``OnPlayerKilled`` callback.
further we could adjust the client connect to:
```
void function OnClientConnected( entity player )
{
	string uid = player.GetUID()
	FFAScoreStruct emptyStruct
	if (  uid in file.ffaPlayerScoreTable ) 
	{
	AddTeamScore( player.GetTeam(), SaveScore[player.GetPlayerName()] )
	player.AddToPlayerGameStat( PGS_ASSAULT_SCORE, ffaPlayerScoreTable[player.GetUID()] )
	}

}
```

Then we have a system where the score is saved for a re joining player AND no one else can get the score

2023-02-19 19:51 UTC, DBmaoha commented
> The code seems a little too complicated for what this can do. If we already have a table of the score of each player, wouldnt it also make sense to then save that score so if they re-join they get to keep their score.
> 
> Also a better way to do this, is to just save the score of a player in a `table < string, int > `. We dont need the struct anyway as the team is unique to each player. I would suggest to just add a callback for player disconnect like this:
> 
> ```
> void function OnPlayerDisconnected(entity player)
> {
> 	ffaPlayerScoreTable[player.GetUID()] <- GameRules_GetTeamScore( player.GetTeam() )
> 
> 	// this prevents a new player to get someone who's left's score
> 	AddTeamScore( player.GetTeam(), -GameRules_GetTeamScore( player.GetTeam() ))
> 
> }
> ```
> 
> That way we can also eliminate the change to the `OnPlayerKilled` callback. further we could adjust the client connect to:
> 
> ```
> void function OnClientConnected( entity player )
> {
> 	string uid = player.GetUID()
> 	FFAScoreStruct emptyStruct
> 	if (  uid in file.ffaPlayerScoreTable ) 
> 	{
> 	AddTeamScore( player.GetTeam(), SaveScore[player.GetPlayerName()] )
> 	player.AddToPlayerGameStat( PGS_ASSAULT_SCORE, ffaPlayerScoreTable[player.GetUID()] )
> 	}
> 
> }
> ```
> 
> Then we have a system where the score is saved for a re joining player AND no one else can get the score

`OnClientDisconnected()` sometimes passes a null entity, and that's why I uses `player.EndSignal( "OnDestroy" )`, use
`AddTeamScore( player.GetTeam(), -GameRules_GetTeamScore( player.GetTeam() ))` should be pretty good

2023-02-20 11:43 UTC, NoCatt approved these changes
Looks good now, I have never experienced any issue with the Client disconnect callback but it really doesnt matter now. imo this is good to merge

2023-02-27 11:01 UTC, uniboi commented on Northstar.CustomServers/mod/scripts/vscripts/gamemodes/_gamemode_ffa.nut
> +	AddTeamScore( team, -GameRules_GetTeamScore( team ))
```suggestion
	AddTeamScore( team, -GameRules_GetTeamScore( team ) )
```
Just some formatting, otherwise the code looks good

2023-02-27 13:29 UTC, uniboi approved these changes
Code looks good, I didn't test the changes though

2023-02-27 13:35 UTC, x3Karma commented
> Code looks good, I didn't test the changes though

sounds suspiciously like "LGTM!"

2023-02-27 13:36 UTC, uniboi commented
It isn't, the code has been improved from "why would you do that" to "this is a valid and efficient way of doing this"

2023-03-02 20:38 UTC, NoCatt commented
Tested in private server with @uniboi. After I rejoined the game all my kills and point were gone 👍

2023-03-02 21:24 UTC, GeckoEidechse approved these changes
Still haven't managed to fix approval counting for reviewers so I'm just giving the approval sign-off to be able to get it merged.

Did not test/check code myself, signing it off as

- Testing was done by @NoCatt and @uniboi 
- Code review was done by @NoCatt and @uniboi

2023-03-02 21:24 UTC, merged