Arc cannon
R2Northstar/NorthstarMods pull request #600
Opened 2023-03-09 01:00 UTC by Masterliberty

Arc Cannon with model, animations, tf1 weapon stats, and bug fixed _arc_cannon file.
![Screenshot (2877)](https://user-images.githubusercontent.com/94194459/223887832-e198ab9f-92a0-492e-9c6a-be7480de25f9.png)

2023-03-09 21:59 UTC, GeckoEidechse requested changes
Current version is missing weapon precaching

See https://github.com/R2Northstar/NorthstarMods/pull/276/files#diff-a449854f2677ae627216b17300ddcde22f3e3788d101a84299689c207cd1cefcR7 for reference on how to add it ^^

2023-03-09 22:43 UTC, GalacticMoblin commented
I would just like to mention I have a custom made Arc Cannon weapon icon I made for Archon.

2023-03-09 22:44 UTC, ASpoonPlaysGames commented
> I would just like to mention I have a custom made Arc Cannon weapon icon I made for Archon.

probably wont get used (yet) because uimg limit

2023-03-16 00:40 UTC, GeckoEidechse reviewed
Some quick one-player testing. Still need to test with other players:

- Arc Cannon is added to the game as intended
- Sound effects appear to still be missing. Separate PR?
- This will break compat both ways between combinations of server/client old/new. There's not a really a fix for this. We will have to version gate it when we release it either way.

To test are still
- [ ] Check the damage effect when getting hit by Arc Cannon
- [x] Have player without Arc Cannon join server with Arc Cannon (I expect them to be unable to connect as mentioned above)

2023-04-24 10:24 UTC, F1F7Y commented
>  Sound effects appear to still be missing. Separate PR?

We can't add new sound effects so just like the triple threat itll have to stay silent

2023-04-24 10:29 UTC, F1F7Y reviewed
From skimming over the code it looks good. Due to this being based on r1 the code quality wont be up to r2 standards, but just like the triple threat this is ok as the game wont be updated with a newer squirrel compiler.

2023-07-11 21:43 UTC, F1F7Y approved these changes
Tested together with #660 on Launcher [#504](https://github.com/R2Northstar/NorthstarLauncher/pull/504)

Works

2023-07-16 20:27 UTC, GeckoEidechse approved these changes
Works in testing. Of note is that this will break compatibility in the following way:

works: ✅
breaks: ❌

|                   | Server old | Server Arc Cannon |
|-------------------|------------|-------------------|
| Client old        | ✅        | ❌                |
| Cleint Arc Cannon | ✅        | ✅                |

2023-07-16 20:27 UTC, GeckoEidechse commented on Northstar.Custom/mod/scripts/vscripts/weapons/mp_titanweapon_arc_cannon.nut
Might commit arc cannon scripts separately first

2023-07-16 21:01 UTC, GeckoEidechse commented
Alright Imma commit the original TF1 files first, then resolve merge conflicts myself and update the PR, then merge

2023-07-16 21:08 UTC, GeckoEidechse commented on Northstar.Custom/mod/scripts/vscripts/weapons/mp_titanweapon_arc_cannon.nut
Done

2023-07-16 21:08 UTC, merged