Clientside toggle for first person embarks/executions
R2Northstar/NorthstarMods pull request #656
Opened 2023-06-25 00:13 UTC by Gityeeter

-Additional convars for enabling first person embarks/executions. 
-Also added Titanfall 1 style executions as a option from classicTitanexecution mod.

https://github.com/R2Northstar/NorthstarMods/assets/94848105/201c4242-6e7b-4e59-8895-0079fe1cd1f3

2023-06-25 09:24 UTC, ASpoonPlaysGames commented
So when you say "Clientside toggle" you just mean that you use convars instead of the playlistvar, and add them to modsettings?

2023-06-25 18:03 UTC, Gityeeter commented
> So when you say "Clientside toggle" you just mean that you use convars instead of the playlistvar, and add them to modsettings?

That is correct. AFAIK you can't change playlistvar from clientside. Convars can be changed even during the middle of a game.

2023-06-26 11:50 UTC, F1F7Y requested changes
Just code formatting, havent tested or read the logic fully yet

2023-06-26 11:50 UTC, F1F7Y commented on Northstar.Custom/mod.json
> +			"DefaultValue": "0"
If you're going to rely on modsettings add the archive flag so they save

2023-06-26 11:50 UTC, F1F7Y commented on Northstar.Custom/mod.json
> +			"RunOn": "CLIENT || UI",
I don't think you need `CLIENT`

2023-06-26 11:50 UTC, F1F7Y commented on Northstar.Custom/mod/scripts/vscripts/embark_settings.nut
> +global function embarkSettings
Should be named `EmbarkSettings_Init` to follow the style of other callbacks

2023-06-26 11:50 UTC, F1F7Y commented on Northstar.Custom/mod/scripts/vscripts/embark_settings.nut
> +    AddConVarSettingEnum("first_person_embark", "Embark", ["Third Person", "First Person"])
Mod settings has been merged and now has differently named functions, use those

2023-06-26 11:50 UTC, F1F7Y commented on Northstar.Custom/mod/scripts/vscripts/melee/_melee_synced_human.gnut
> +
Unnecessary whitespace changes in this file

2023-06-26 11:50 UTC, F1F7Y commented on Northstar.Custom/mod/scripts/vscripts/melee/_melee_synced_titan.gnut
> +	print(GetConVarInt("execution_style"))
No need to print

2023-06-26 11:50 UTC, F1F7Y commented on Northstar.Custom/mod/scripts/vscripts/melee/_melee_synced_titan.gnut
> +	if ( GetConVarInt("execution_style") == 2 )
Should be an enum to make the code more readable imo

2023-06-26 11:50 UTC, F1F7Y commented on Northstar.Custom/mod/scripts/vscripts/titan/sh_titan_embark.gnut
> +#endif
again

2023-07-09 20:05 UTC, F1F7Y commented
> -Additional convars for enabling first person embarks/executions.
> -Also added Titanfall 1 style executions as a option from classicTitanexecution mod.

Should be separate PRs

2023-08-17 22:58 UTC, closed without merging