Doublebarrel
R2Northstar/NorthstarMods pull request #660
Opened 2023-06-29 20:36 UTC by EM4Volts

Video ingame:
https://cdn.discordapp.com/attachments/1121520467791056997/1124063836702523422/yeet.mp4

all stats have been brought over from TFO aswell.
should make people more happy when playing neinguars gungame as it features said weapon but used the weapons placeholder model (a mastiff).

Replace this line with a description of your change (and screenshots/screenrecordings if applicable).

reload speed in video is slower in vid then ingame as video was made after the reload was made to fit the tfo reload

2023-07-04 15:37 UTC, EM4Volts commented
all materials have now been packed into a vpk,
as for renaming the rpak i dont know if that is going to be a good idea
because recently someone tried extracting one of my rpaks and the images inside were a bit broken/shifted afterwards so i think seperate might be better rn.

2023-07-04 17:19 UTC, ASpoonPlaysGames commented
> Going by current structure `.vtf` and `.vmt` fies should be packed in the vpk

No? Those have been able to be loaded from disk for a while (and mod settings doesnt pack its vmt and vtf into vpk)

2023-07-04 18:39 UTC, F1F7Y commented
> No? Those have been able to be loaded from disk for a while (and mod settings doesnt pack its vmt and vtf into vpk)

I know we can ship these without packing them into a vpk, but so far all materials have been packed into `client_mp_northstar_custom.vpk`.

We either ship everything in the vpk or we ship everything outside as separate files.

2023-07-04 18:40 UTC, ASpoonPlaysGames commented
> I know we can ship these without packing them into a vpk, but so far all materials have been packed into `client_mp_northstar_custom.vpk`.

https://github.com/R2Northstar/NorthstarMods/tree/main/Northstar.Client/mod/materials/vgui would like a word

2023-07-04 18:41 UTC, ASpoonPlaysGames commented
But also, those materials were added to the vpk because at the time we couldnt load vmts from disk.

2023-07-05 01:08 UTC, EM4Volts commented
should i leave the vmt/vft inside of the vpk now or change it to be outside again?

2023-07-09 10:54 UTC, ASpoonPlaysGames commented
> should i leave the vmt/vft inside of the vpk now or change it to be outside again?

Just leave it for now. I might make a separate PR to move everything outside of VPKs (in repo and then put them in VPKs in CI) but that's beyond the scope of this PR.

2023-07-09 12:21 UTC, EM4Volts commented
> > should i leave the vmt/vft inside of the vpk now or change it to be outside again?
> 
> Just leave it for now. I might make a separate PR to move everything outside of VPKs (in repo and then put them in VPKs in CI) but that's beyond the scope of this PR.

ok, as said, didnt quite know wether im now supposed to put them in a vpk or not lol

2023-07-09 20:00 UTC, F1F7Y requested changes
I'm fine with things as they are rn, but would prefer if the rpak was named after the gun script ( eg `mp_weapon_shotgun_doublebarrel` )

2023-07-09 20:03 UTC, ASpoonPlaysGames commented
> I'm fine with things as they are rn, but would prefer if the rpak was named after the gun script ( eg `mp_weapon_shotgun_doublebarrel` )

Fair warning, if you do this rebuild the rpak with the new name. Just renaming the file won't work (it'll try to load the starpak with the original name)

2023-07-10 15:43 UTC, F1F7Y requested changes
After going through this once again:
1. The path to the mdl should be `models/weapons/weapon_shotgun_doublebarrel/`
2. The name of the mdl should be `ptpov_shotgun_doublebarrel.mdl`
3. The name of the rpak should be `weapon_shotgun_doublebarrel.rpak` ( or something similar to the script name

~~This is also missing a call to `PrecacheWeapon` in `ns_northstar_custom_precache.gnut`~~
And current version as of this review is crashing due to no `rpak.json`

Most of these names i based off of other custom weapons.

2023-07-10 16:02 UTC, ASpoonPlaysGames commented
Wait we don't have the third person model? :(

2023-07-10 16:03 UTC, ASpoonPlaysGames commented
> 3\. The name of the rpak should be `weapon_shotgun_doublebarrel.rpak` ( or something similar to the script name

For the sake of readability, just keep it identical to script name (`mp_weapon_shotgun_doublebarrel.rpak`)

2023-07-11 01:03 UTC, EM4Volts commented
rpaks should be named correctly in my doublebarrel branch now, also added a world model

2023-07-11 14:42 UTC, F1F7Y commented
> rpaks should be named correctly in my doublebarrel branch now, also added a world model

could you also rename the folder and the mdls like i suggested in my last review

2023-07-11 19:17 UTC, F1F7Y commented
> the foldername is the same as in tfo, thats why i kept it.

we're not Nexon ( thankfully )

2023-07-11 21:44 UTC, F1F7Y reviewed
Tested together with #600  on Launcher [#504](https://github.com/R2Northstar/NorthstarLauncher/pull/504)

Works

Will approve once the folders and mdls are renamed

2023-07-12 03:54 UTC, EM4Volts commented
rename done

2023-07-12 11:28 UTC, p0358 commented
Does it belong to the main mod though? Sounds like an ideal use-case for the fancy mod auto-download system that they were working on innit

2023-07-12 11:34 UTC, F1F7Y commented
> Does it belong to the main mod though? Sounds like an ideal use-case for the fancy mod auto-download system that they were working on innit

I think you confused your nationality, instead of "innit" you should have ended the sentence with "xd"

To answer your question you can make the same point for everything in Northstar.Custom. Including it in Northstar means more people will be able to use it without having to figure out how mods work. Second point would be that auto-download is stuck in PR hell ig

2023-07-12 11:36 UTC, F1F7Y approved these changes
Works

2023-07-12 11:36 UTC, F1F7Y commented
@GeckoEidechse adds vanilla file `mp_weapon_shotgun_doublebarrel.txt` from mp_common

2023-07-12 18:04 UTC, p0358 commented
> I think you confused your nationality, instead of "innit" you should have ended the sentence with "xd"

shut up xd

2023-07-16 21:56 UTC, EM4Volts commented
was tested with others on desynced servers (servers without the mod)

crashes users with mod if someone without it holds it in hands.

2023-07-16 22:27 UTC, GeckoEidechse approved these changes
Compatibility in matrix

|                           | old server  | server with double barrel |
| ------------------------- | ----------- | ------------------------- |
| old client                | works       | error mdl model           |
| client with double barrel | client crashes for some reason but only when someone has the gun equipped | works |

2023-07-17 00:04 UTC, GeckoEidechse commented on Northstar.Custom/mod/scripts/weapons/mp_weapon_shotgun_doublebarrel.txt
Waiting on https://github.com/EM4Volts/NorthstarMods/pull/1

2023-07-17 00:07 UTC, GeckoEidechse commented
So while looking through this I noticed that original version had segmented reload which honestly I think it makes sense for this gun. Now the issue is that I have no idea how to get that working. Tried to use some of the original values but without success :/

2023-07-17 19:05 UTC, F1F7Y approved these changes
Works like a gun

2023-07-17 20:18 UTC, EM4Volts commented
> So while looking through this I noticed that original version had segmented reload which honestly I think it makes sense for this gun. Now the issue is that I have no idea how to get that working. Tried to use some of the original values but without success :/

i attempted todo so but i couldnt get it to work, tried replicating the way the mastiff does it but something is borked i guess.

2023-07-17 20:54 UTC, H0L0theBard approved these changes
LGTM (Looks gun to me) :)

2023-07-18 11:29 UTC, GeckoEidechse commented
I'd say we do like a playtest with 2-3 people again tonight and then merge

2023-07-18 23:41 UTC, GeckoEidechse approved these changes
Re-tested in private match with @uniboi. Gun is a bit OP in damage but values are copied (and reduced) from TFO so I guess it's fine ¯\\\_(ツ)\_/¯

2023-07-18 23:41 UTC, merged