Remove annoying recurring print from chatroom.nut
R2Northstar/NorthstarMods pull request #676
Opened 2023-07-30 16:00 UTC by JMM889901

First commit is upload from vanilla

2023-07-30 16:01 UTC, ASpoonPlaysGames approved these changes
Holy shit yes please thank you oh my god (also, code looks good)

2023-07-30 16:02 UTC, ASpoonPlaysGames commented
> First commit is upload from vanilla

you should mention which vpk this is from

2023-07-30 16:02 UTC, JMM889901 commented
> you should mention which vpk this is from

read first commit description :)

2023-07-30 16:03 UTC, F1F7Y requested changes
I know I'm nitpicking but imo it would be better to just comment it out instead of removing it out right

2023-07-30 16:03 UTC, uniboi approved these changes
praise the lord

> you should mention which vpk this is from

click the commit bruh it's right there

2023-07-30 16:03 UTC, ASpoonPlaysGames commented
> click the commit bruh it's right there

(this is for gecko not for me)

2023-07-30 16:06 UTC, JMM889901 commented
> I know I'm nitpicking but imo it would be better to just comment it out instead of removing it out right

👍 done

2023-07-30 16:08 UTC, F1F7Y approved these changes
Changes look good

2023-07-30 19:57 UTC, GeckoEidechse commented
For completeness sake, maybe add sample log snippet that shows before/after change. That sorta stuff helps a lot with figuring out which PRs should get priority ;)

2023-07-30 20:01 UTC, JMM889901 commented
![image](https://github.com/R2Northstar/NorthstarMods/assets/41163714/8d8943a9-8406-4797-8e7c-46c24ece90fb)

before^ 

after is kinda hard to show since its just the absence of those prints

2023-08-11 20:11 UTC, JMM889901 commented
boowomp

2023-08-24 19:43 UTC, EladNLG approved these changes
oh my god

2023-10-03 22:33 UTC, GeckoEidechse commented on Northstar.Client/mod/scripts/vscripts/ui/chatroom.nut
> +	//printt( "Showing user info for UID " + userId + " on hardware " + hardware )
```suggestion
	// printt( "Showing user info for UID " + userId + " on hardware " + hardware )
```

2023-10-03 22:36 UTC, GeckoEidechse commented
Merging based on previous reviews. Made sure to commit vanilla file to `main` separately first.

2023-10-03 22:37 UTC, merged