Add Winter holiday event models to the lobby
R2Northstar/NorthstarMods pull request #768
Opened 2023-12-03 21:00 UTC by RoyalBlue1

Models will be shown from 18.12 to the 06.01
![image](https://github.com/R2Northstar/NorthstarMods/assets/11448698/ee0aba32-0a94-4deb-a402-4f97ff9b5da3)
![image](https://github.com/R2Northstar/NorthstarMods/assets/11448698/b97b425c-31d9-4697-9cd2-c3ef6a3ac3e2)

the tree model is from r5 and modified by 4Volt
The other models are from 4Volt
Co-authored-by: EM4Volts <87427011+EM4Volts@users.noreply.github.com>

2023-12-04 14:46 UTC, Alystrasz requested changes
Apart from formatting, this looks good.
I could test this by modifying the date, and verify new models appear in the lobby.

![image](https://github.com/R2Northstar/NorthstarMods/assets/11993538/47af1795-3964-45f4-8e4b-d84abc371eb0)

![image](https://github.com/R2Northstar/NorthstarMods/assets/11993538/57f491e5-f1ce-448a-96fe-9a3fe78ff030)

Private lobby menu is however hard to read white-on-white, I don't know how this could be fixed (rotating the camera upwards maybe? Adding another present just below menu position?)

2023-12-04 15:10 UTC, ASpoonPlaysGames commented on Northstar.Custom/paks/rpak.json
> +        "snow.rpak": "common.rpak"
its a tabs vs spaces issue, top stuff is tabs

2023-12-04 15:35 UTC, RoyalBlue1 commented on Northstar.Custom/paks/rpak.json
> +        "snow.rpak": "common.rpak"
should be all tabs now

2023-12-04 18:15 UTC, GeckoEidechse commented on Northstar.Custom/paks/rpak.json
> +        "snow.rpak": "common.rpak"
I swear, I'll just secretly push a whitespace change at some point given how many times we had issues with mixed whitespaces so far >:)

2023-12-07 10:47 UTC, ASpoonPlaysGames requested changes

2023-12-07 10:47 UTC, ASpoonPlaysGames commented on Northstar.Custom/mod/scripts/vscripts/sh_event_models.gnut
> +global function EventModelsInit
Why is this a shared file? Aren't things that server precaches automatically precached by clients?

2023-12-07 10:47 UTC, ASpoonPlaysGames commented on Northstar.Custom/mod/scripts/vscripts/ui_ns_custom_mod_settings.gnut
> +global function NSCustomModSettings
I would move this to the ui folder and drop the `ui_` prefix personally

2023-12-07 15:13 UTC, EM4Volts commented
> Private lobby menu is however hard to read white-on-white, I don't know how this could be fixed (rotating the camera upwards maybe? Adding another present just below menu position?)

i think blue tried looking into moving cam or something. in the end we decided on sticking with this. since one menu is usable in other menus aswell, and the other is the store which isnt usable anyway. its a small time window and u can also still use the menu if u hover over it as the button label colors change then.

2023-12-08 02:29 UTC, RoyalBlue1 commented
the camera is set through an animation so we would either use one of the other animations or modify the animation but that would be permanent

2023-12-08 16:34 UTC, EM4Volts commented
> the camera is set through animations so we have 2 Options 1 use one of the other animations 2 modify the animation both are not really that good of an option and without writing a whole new api changing it would do it permanently


i dont think changing it would be bad. maybe we can sit together in the coming days and work out a solution for it.
currently the vanilla screen is just blank aswell so changing the camera to maybe face 180 degree wouldnt really change what stuff looks like

2023-12-12 01:39 UTC, ASpoonPlaysGames approved these changes
Code looks good

2023-12-13 15:51 UTC, EM4Volts commented
"needs testing" just tested by changing the dates in scrippt to trigger early. works.

2023-12-13 16:11 UTC, GeckoEidechse commented
> missing some localisation

Missing localisations are easier to add post-merge actually as they are picked up by [weblate](https://translate.harmony.tf/projects/northstar/client/) which is way more accessible to non-developers than GitHub anyway ^^

2023-12-13 17:58 UTC, ASpoonPlaysGames commented
> Missing localisations are easier to add post-merge actually as they are picked up by [weblate](https://translate.harmony.tf/projects/northstar/client/) which is way more accessible to non-developers than GitHub anyway ^^

Nah, because like its just using string literals, so it can't be localised atm.

We can still just fix this later very easily but yeah

2023-12-13 23:56 UTC, GeckoEidechse requested changes

2023-12-13 23:56 UTC, GeckoEidechse commented on Northstar.Custom/mod/scripts/vscripts/_event_models.gnut
> +	if( ( ( month == 12 ) && ( day >= 18 ) ) || ( ( month == 1 ) && ( day <= 6 ) ) )
Time range is kinda obvious but I'd still add a comment to it
```suggestion
	// 18th December to 6th January
	if( ( ( month == 12 ) && ( day >= 18 ) ) || ( ( month == 1 ) && ( day <= 6 ) ) )
```

2023-12-13 23:56 UTC, GeckoEidechse commented on Northstar.Custom/mod/models/northstar/floor.mdl
Should best be named something like `christmas-floor.mdl` or `snow-floor.mdl` or something so we don't have any conflicts when we add more event related stuff in the future.

2023-12-13 23:58 UTC, GeckoEidechse commented on Northstar.Custom/mod/materials/models/northstartree/lightsflicker.vtf
Why is one in `.../northstartree/...` and one in `.../northstar/...` subdir?

(Like the parent paths are different but I feel like the substring of the path should somewhat match up so that it's clear they belong together or sth)

2023-12-14 00:20 UTC, GeckoEidechse commented on Northstar.Custom/mod/materials/models/northstartree/lightsflicker.vtf
Done with 134dc3f60f4f480757de9ab0f8cd152d202caf16

2023-12-14 00:20 UTC, GeckoEidechse commented on Northstar.Custom/mod/models/northstar/floor.mdl
Done with 134dc3f60f4f480757de9ab0f8cd152d202caf16

2023-12-14 00:29 UTC, GeckoEidechse approved these changes
Requests from reviews have been addressed.

2023-12-14 00:31 UTC, merged