fix crash when player got a special team
R2Northstar/NorthstarMods pull request #866
Opened 2024-09-04 23:04 UTC by LightBlueCube

![QQ图片20240905070404](https://github.com/user-attachments/assets/447b5396-e7c4-4557-8ef7-630adb6f052a)

2024-09-05 01:11 UTC, Zanieon requested changes

2024-09-05 01:11 UTC, Zanieon commented on Northstar.CustomServers/mod/scripts/vscripts/mp/_gamestate_mp.nut
> +	if( [ TEAM_IMC, TEAM_MILITIA ].contains( player.GetTeam() ) )
```suggestion
	if( IsIMCOrMilitiaTeam( player.GetTeam() ) )
```
Utility function that exactly serves this purpose.

2024-09-05 17:59 UTC, Zanieon approved these changes
Code looks good, and this will probably solve problems in regards to any gamemode isn't 2 sided based, or even if they partially uses Militia or IMC teams, it will work only between those teams.

2024-09-06 07:11 UTC, GeckoEidechse commented
Uh, what's the command to switch player teams again so that I can test this? ^^"

2024-09-06 09:09 UTC, Zanieon commented
> Uh, what's the command to switch player teams again so that I can test this? ^^"

There's no default way of doing it right now, you can only do either by using FSU and typing `!switch` in chat, or using my FD branch and typing `changeteam` in console.

2024-09-06 10:32 UTC, F1F7Y commented
You could also do smth like `script SetTeam(GetPlayerArray()[0], GetOtherTeam(GetPlayerArray()[0].GetTeam()))` ( <- this prob dont work as i dont remember the exact funcs )

2024-09-06 11:18 UTC, LightBlueCube commented
> Uh, what's the command to switch player teams again so that I can test this? ^^"

u can try use this function
```
void function SetTeam( entity ent, int team )
```
just like this comment

> You could also do smth like `script SetTeam(GetPlayerArray()[0], GetOtherTeam(GetPlayerArray()[0].GetTeam()))` ( <- this prob dont work as i dont remember the exact funcs )

here is some team name u may need to know
TEAM_ANY, TEAM_INVALID, TEAM_UNASSIGNED, TEAM_SPECTATOR, TEAM_IMC, TEAM_MILITIA, TEAM_BOTH

2024-09-09 20:12 UTC, Zanieon commented
Tested this by using #872 and playing Free For All, so far server didn't complain, and probably it wouldn't as there's sanity checks in that team changing code.

Besides... Only FFA Scoreboard supports more than 2 teams, all other gamemodes will crash clients that tries to open Scoreboard if trying to assign players to other than `TEAM_MILITIA` or `TEAM_IMC` teams

I also have to mention that i prefer this to get merged first over #875 so i can update the function there manually as Github probably will get confused and do a merge conflict for either PRs that gets merged last.

2024-09-09 22:23 UTC, GeckoEidechse commented
Merging based on reviews, thanks @Zanieon

2024-09-09 22:26 UTC, merged