fix some small bugs for gamemode fw
R2Northstar/NorthstarMods pull request #868
Opened 2024-09-06 02:40 UTC by LightBlueCube

i only tested these changes on my own server running at NorthstarCN
not really sure is it working normally at here
i will very appreciate if anyone can test it
also sorry for my bad English
![QQ图片20240906104002](https://github.com/user-attachments/assets/d9cb419c-8506-4c71-9273-b5ea3cd14022)

2024-09-07 22:54 UTC, ASpoonPlaysGames requested changes
Formatting stuff

2024-09-07 22:54 UTC, ASpoonPlaysGames commented on Northstar.Custom/mod/scripts/vscripts/gamemodes/_gamemode_fw.nut
> +	if( GetMapName() == "mp_thaw" )
```suggestion
	if ( GetMapName() == "mp_thaw" )
```

2024-09-07 22:54 UTC, ASpoonPlaysGames commented on Northstar.Custom/mod/scripts/vscripts/gamemodes/_gamemode_fw.nut
> +    int newShield = int ( min( turret.GetShieldHealthMax(), turret.GetShieldHealth() + ( turret.GetShieldHealthMax() * GetCurrentPlaylistVarFloat( "fw_turret_fixed_shield", TURRET_FIXED_SHIELD_PERCEN
```suggestion
    int newShield = int( min( turret.GetShieldHealthMax(), turret.GetShieldHealth() + ( turret.GetShieldHealthMax() * GetCurrentPlaylistVarFloat( "fw_turret_fixed_shield", TURRET_FIXED_SHIELD_PERCENTAGE ) ) ) )
```

2024-09-07 22:56 UTC, ASpoonPlaysGames approved these changes
Code looks good :)

2024-10-12 04:26 UTC, closed without merging

2024-10-12 08:47 UTC, GeckoEidechse commented
Why was that closed? ^^"

2024-10-18 12:16 UTC, LightBlueCube commented
> Why was that closed? ^^"

i deleted my repo cuz i though its all finished, really sorry i didnt see the notifications
ill make a new pr or try fix this one i guess