Remove Data Centers from Main Menu
R2Northstar/NorthstarMods pull request #909
Opened 2024-11-30 01:01 UTC by Zanieon

We actually don't use them at all, there's no reason for the button to stay there, plenty of people do actually think they connect into Northstar servers through them only because the button is still there, when in fact it has zero impact on anything.

2024-11-30 01:03 UTC, Zanieon commented
Imma bypass the labels because it's literally one-line change, just gonna wait for people to approve so it can get merged.

2024-11-30 03:01 UTC, NachosChipeados approved these changes
Works fine, game doesn't magically explode when opening the main menu

2024-11-30 10:01 UTC, ASpoonPlaysGames requested changes
This doesn't handle `-vanilla`

Granted, a lot of things currently dont handle it, but I'd rather not add more to the pile

2024-11-30 11:35 UTC, ASpoonPlaysGames commented
> @ASpoonPlaysGames Add the const to the compile check smh

Is it not there already? I won't be at my pc today, @GeckoEidechse any chance you could add it?

2024-11-30 13:18 UTC, GeckoEidechse commented
Sadly won't get the chance today :/
Also, how do I even do that? ^^"

2024-11-30 14:00 UTC, ASpoonPlaysGames commented
Oh wait this might need an update to the GH action

2024-12-05 11:47 UTC, GeckoEidechse commented
@ASpoonPlaysGames bump

2024-12-07 14:40 UTC, ASpoonPlaysGames approved these changes
Code looks good

2025-01-01 23:51 UTC, merged